// <auto-generated />
namespace MyFinance.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class increaseValuePrecision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(increaseValuePrecision));
        
        string IMigrationMetadata.Id
        {
            get { return "201404091904572_increaseValuePrecision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
