// <auto-generated />
namespace MyFinance.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class adddateWithdrawfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddateWithdrawfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201405161440167_add-dateWithdraw-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
