// <auto-generated />
namespace MyFinance.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addFundType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFundType));
        
        string IMigrationMetadata.Id
        {
            get { return "201404150031536_addFundType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
